# Generated by Django 5.0.1 on 2024-04-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra_issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infraissue',
            old_name='complex',
            new_name='complex_name',
        ),
    ]
